stages:
  - lint
  - test

linting:
  stage: lint
  script:
    - flake8
    - interrogate -v --ignore-init-method --ignore-module --ignore-nested-functions --ignore-regex "__repr__" --fail-under 50 mmseg


building:
  stage: test
  script:
    - python setup.py check -m -s
    - python -m pip install -e .

testing:
  stage: test
  script:
    - python -m coverage run --branch --source mmseg -m pytest tests/
    - python -m coverage xml
    - python -m coverage report -m
