stages:
  - lint
  - test

linting:
  stage: lint
  script:
    - flake8

building:
  stage: test
  script:
    - python setup.py check -m -s
    - python -m pip install -e .

testing:
  stage: test
  script:
    - python -m coverage run --branch --source mmcv -m pytest tests/
    - python -m coverage xml
    - python -m coverage report -m
